version: "3.8"
services:
  mongodb:
    image: 'mongo'
    container_name: mongodb
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongodb.env
      
  backend:
    build: ./backend #Path to Dockerfile
    container_name: backend
    image: backend:node
    ports:
      - '5000:5000'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb 

  frontend:
    build: ./frontend
    container_name: frontend
    image: frontend:react
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true 
    tty: true 
    depends_on:
      - backend
   
volumes:
  data:
  logs:
